DIKE_STATE_BUSY = 1
DIKE_STATE_EMPTY = 2

TINY_SIZE = 1
MEDIUM_SIZE = 2
LARGE_SIZE = 4

POSSIBLE_SIZES = [
    TINY_SIZE,
    MEDIUM_SIZE,
    LARGE_SIZE,
]

INTERVAL_RANGES = [
    (0, 180),
    (180, 540),
    (540, 720),
]

INITIAL_TIME = INTERVAL_RANGES[0][0]
FINAL_TIME = INTERVAL_RANGES[-1][1]

NORMAL_PARAMETERS = {
    (TINY_SIZE,   INTERVAL_RANGES[0]): (5,  2),
    (MEDIUM_SIZE, INTERVAL_RANGES[0]): (15, 3),
    (LARGE_SIZE,  INTERVAL_RANGES[0]): (45, 3),

    (TINY_SIZE,   INTERVAL_RANGES[1]): (3,  1),
    (MEDIUM_SIZE, INTERVAL_RANGES[1]): (10, 5),
    (LARGE_SIZE,  INTERVAL_RANGES[1]): (35, 7),

    (TINY_SIZE,   INTERVAL_RANGES[2]): (10, 2),
    (MEDIUM_SIZE, INTERVAL_RANGES[2]): (20, 5),
    (LARGE_SIZE,  INTERVAL_RANGES[2]): (60, 9),
}
